export default function () {
  return [
    {title: 'Javascript: The Good Parts'},
    {title: 'Harry Potter'},
    {title: 'The Dark Tower'},
    {title: 'Eloquent Ruby'}
  ]
}

/*
A reducer is a function that returns a piece of the application state (app state is generated by reducer funcs)
b/c our app can many pieces of state, we can have many reducers
*/
